"""CLI: run the full Big Data pipeline and emit a combined report.

Runs corpus analytics + the inverted-index/BM25 build (+ an optional distributed
BM25 query) on a single engine over one corpus, then writes ``analytics.json``,
``bm25_stats.json`` and a human-readable ``REPORT.md``.

    python -m bigdata.run_all --corpus macro --query "inflation interest rates"
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from bigdata.cli_common import (  # noqa: E402
    Timer,
    add_common_args,
    build_engine,
    load_dataset,
    resolve_output_dir,
    run_context,
    write_csv,
    write_json,
)
from bigdata.jobs import corpus_analytics, inverted_index  # noqa: E402


def _markdown_report(corpus: str, engine_name: str, analytics: dict, stats: dict, query: str | None, query_rows: list) -> str:
    lines: list[str] = []
    lines.append(f"# Big Data corpus report -- `{corpus}`")
    lines.append("")
    lines.append(f"- Engine: **{engine_name}**")
    lines.append(f"- Documents: **{analytics.get('total_documents', 0):,}**")
    lines.append(f"- Vocabulary (distinct terms): **{stats.get('vocabulary_size', 0):,}**")
    lines.append(f"- Total tokens: **{stats.get('total_tokens', 0):,}**")
    lines.append(f"- Average document length: **{stats.get('average_document_length', 0):.1f}** tokens")
    pit = analytics.get("point_in_time", {})
    lines.append(f"- Point-in-time window: `{pit.get('min_available_at', '')}` -> `{pit.get('max_available_at', '')}`")
    lines.append("")

    def table(title: str, mapping: dict, key_header: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"| {key_header} | count |")
        lines.append("| --- | ---: |")
        for name, count in mapping.items():
            lines.append(f"| {name} | {count:,} |")
        lines.append("")

    table("Documents by source family", analytics.get("by_source_family", {}), "source_family")
    table("Documents by year", analytics.get("by_year", {}), "year")

    def top_table(title: str, rows: list, key_header: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"| {key_header} | count |")
        lines.append("| --- | ---: |")
        for row in rows[:15]:
            lines.append(f"| {row['name']} | {row['count']:,} |")
        lines.append("")

    top_table("Top tickers", analytics.get("top_tickers", []), "ticker")
    top_table("Top event tags", analytics.get("top_event_tags", []), "event_tag")
    top_table("Top risk terms", analytics.get("top_risk_terms", []), "risk_term")

    lines.append("## Top terms by document frequency (inverted index)")
    lines.append("")
    lines.append("| term | df |")
    lines.append("| --- | ---: |")
    for entry in stats.get("top_terms_by_document_frequency", [])[:20]:
        lines.append(f"| {entry['term']} | {entry['document_frequency']:,} |")
    lines.append("")

    if query:
        lines.append(f"## Distributed BM25 query demo -- `{query}`")
        lines.append("")
        lines.append("| rank | doc_id | bm25_score |")
        lines.append("| ---: | --- | ---: |")
        for rank, row in enumerate(query_rows[:10], start=1):
            lines.append(f"| {rank} | {row['doc_id']} | {row['bm25_score']:.4f} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by `bigdata.run_all`. Compute ran distributed on the engine above; "
                 "small aggregate results were collected to the driver and written with Python._")
    return "\n".join(lines) + "\n"


def main(argv: list | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the full Big Data pipeline and write a report.")
    add_common_args(parser)
    parser.add_argument("--query", default=None, help="Optional BM25 query scored distributed for the report.")
    parser.add_argument("--query-top-k", type=int, default=10)
    parser.add_argument("--top-n", type=int, default=25)
    parser.add_argument("--top-terms", type=int, default=50)
    args = parser.parse_args(argv)

    output_dir = resolve_output_dir(args, "report")
    context = run_context(args, "run_all")

    engine = build_engine(args)
    context["engine_used"] = engine.name
    print(f"[bigdata] full pipeline | engine={engine.name} corpus={args.corpus}", flush=True)
    try:
        dataset, corpus_path = load_dataset(engine, args)
        dataset = dataset.cache()
        context["corpus_path"] = str(corpus_path)

        with Timer() as t_an:
            analytics = corpus_analytics.compute_analytics(dataset, top_n=args.top_n)
        with Timer() as t_ix:
            stats = inverted_index.build_bm25_index(dataset, top_terms=args.top_terms)

        query_rows: list = []
        if args.query:
            scored = inverted_index.query_bm25(dataset, args.query, stats, top_k=args.query_top_k)
            query_rows = [{"doc_id": d, "bm25_score": round(s, 6)} for d, s in scored]

        context["analytics_seconds"] = round(t_an.seconds, 3)
        context["index_seconds"] = round(t_ix.seconds, 3)

        analytics["run"] = context
        stats_summary = {k: v for k, v in stats.items() if k not in ("document_frequencies", "document_lengths")}
        stats_summary["run"] = context

        write_json(output_dir / "analytics.json", analytics)
        write_json(output_dir / "bm25_stats.json", stats_summary)
        write_csv(
            output_dir / "document_frequencies.csv",
            ["term", "document_frequency"],
            sorted(stats["document_frequencies"].items(), key=lambda kv: (-kv[1], kv[0])),
        )
        if args.query:
            write_json(output_dir / "query_demo.json", {"query": args.query, "results": query_rows})

        report_md = _markdown_report(args.corpus, engine.name, analytics, stats_summary, args.query, query_rows)
        (output_dir / "REPORT.md").write_text(report_md, encoding="utf-8")
    finally:
        engine.stop()

    print(json.dumps({
        "engine": engine.name,
        "corpus": str(corpus_path),
        "total_documents": analytics.get("total_documents"),
        "vocabulary_size": stats_summary.get("vocabulary_size"),
        "analytics_seconds": context["analytics_seconds"],
        "index_seconds": context["index_seconds"],
        "output_dir": str(output_dir),
        "report": str(output_dir / "REPORT.md"),
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
