"""Runtime helpers for one-seed PPO text-feature screening notebooks.

The notebooks generated by prepare_huawei_ppo_screening_package.py import this
module on Huawei Cloud.  It keeps the notebook cells small while preserving the
existing PPO runner from the external Ablation Ladder v2 project.
"""

from __future__ import annotations

import json
import os
import sys
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence


DEFAULT_PACKAGE_RELATIVE_PATH = Path(
    "FinPortfolio_IR",
    "data",
    "exports",
    "daily_retrieval_ppo_full_dis_legacy",
    "ppo_ablation_package",
    "huawei_screening_seed42",
)
MANIFEST_NAME = "huawei_ppo_screening_manifest.json"

BASE_FEATURE_COLUMNS: tuple[str, ...] = (
    "daily_return",
    "atr_rel",
    "macd",
    "rsi_30",
    "cci_30",
    "dx_30",
    "volume_ratio",
    "obv_pct_change",
    "turbulence",
)
MACRO_FEATURE_COLUMNS: tuple[str, ...] = (
    "10Y_Yield",
    "VIX",
    "SP500_Trend",
)

CUSTOM_TEXT_FEATURE_SETS: dict[str, dict[str, str]] = {
    "base_macro_plus_text_lean_v1": {
        "group_name": "text_lean_v1",
        "feature_family": "fingpt_text_lean_v1",
        "description": (
            "Base macro PPO observation set plus lean FinIR/FinGPT text features "
            "screened on forward risk diagnostics."
        ),
    },
    "base_macro_plus_text_action_primitive_v1": {
        "group_name": "text_action_primitive_v1",
        "feature_family": "fingpt_text_action_primitive_v1",
        "description": (
            "Base macro PPO observation set plus FinIR/FinGPT text features screened "
            "against teacher actions and latent behavior primitives."
        ),
    },
}


def _dedupe(values: Sequence[str]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(str(value) for value in values))


def _candidate_ancestors(start: Path, limit: int = 8) -> list[Path]:
    current = start.resolve()
    out = [current]
    for _ in range(limit):
        parent = current.parent
        if parent == current:
            break
        out.append(parent)
        current = parent
    return out


def _first_existing(candidates: Sequence[Path], *, expected_file: str | None = None) -> Path | None:
    for candidate in candidates:
        path = candidate.expanduser().resolve()
        if expected_file:
            if (path / expected_file).exists():
                return path
        elif path.exists():
            return path
    return None


def resolve_package_dir(project_root: str | Path | None = None, package_dir: str | Path | None = None) -> Path:
    if package_dir:
        resolved = Path(package_dir).expanduser().resolve()
        if not (resolved / MANIFEST_NAME).exists():
            raise FileNotFoundError(f"Manifest not found in explicit package_dir: {resolved}")
        return resolved

    root = Path(project_root or Path.cwd()).expanduser().resolve()
    candidates: list[Path] = []
    env_value = os.environ.get("HUAWEI_PPO_SCREENING_PACKAGE_DIR")
    if env_value:
        candidates.append(Path(env_value))
    for ancestor in _candidate_ancestors(root):
        candidates.extend(
            [
                ancestor,
                ancestor / "huawei_screening_seed42",
                ancestor / "ppo_ablation_package" / "huawei_screening_seed42",
                ancestor / DEFAULT_PACKAGE_RELATIVE_PATH,
            ]
        )
    found = _first_existing(candidates, expected_file=MANIFEST_NAME)
    if found is None:
        raise FileNotFoundError(
            "Could not locate huawei_ppo_screening_manifest.json. "
            "Set HUAWEI_PPO_SCREENING_PACKAGE_DIR or pass package_dir explicitly."
        )
    return found


def load_manifest(package_dir: str | Path) -> dict[str, Any]:
    path = Path(package_dir) / MANIFEST_NAME
    return json.loads(path.read_text(encoding="utf-8"))


def get_experiment(manifest: Mapping[str, Any], variant_name: str) -> dict[str, Any]:
    for experiment in manifest.get("experiments", []):
        if str(experiment.get("name")) == str(variant_name):
            return dict(experiment)
    known = [str(item.get("name")) for item in manifest.get("experiments", [])]
    raise KeyError(f"Unknown experiment variant {variant_name!r}. Known variants: {known}")


def resolve_ablation_root(project_root: str | Path | None = None, ablation_root: str | Path | None = None) -> Path:
    if ablation_root:
        resolved = Path(ablation_root).expanduser().resolve()
        if not (resolved / "dow30_notebook_research_runner.py").exists():
            raise FileNotFoundError(f"Ablation Ladder v2 runner not found in: {resolved}")
        return resolved

    root = Path(project_root or Path.cwd()).expanduser().resolve()
    candidates: list[Path] = []
    env_value = os.environ.get("DOW30_ABLATION_ROOT")
    if env_value:
        candidates.append(Path(env_value))
    for ancestor in _candidate_ancestors(root):
        candidates.extend(
            [
                ancestor / "Ablation Ladder v2",
                ancestor / "GITHUB" / "Ablation Ladder v2",
                ancestor / "RL for Time-Series Forecasting" / "GITHUB" / "Ablation Ladder v2",
            ]
        )
    candidates.append(Path(r"C:\Users\ivanp\RL for Time-Series Forecasting\GITHUB\Ablation Ladder v2"))
    found = _first_existing(candidates, expected_file="dow30_notebook_research_runner.py")
    if found is None:
        raise FileNotFoundError(
            "Could not locate Ablation Ladder v2. Set DOW30_ABLATION_ROOT or pass ablation_root explicitly."
        )
    return found


def resolve_dataset_path(
    manifest: Mapping[str, Any],
    package_dir: str | Path,
    project_root: str | Path | None = None,
    dataset_path: str | Path | None = None,
) -> Path:
    if dataset_path:
        resolved = Path(dataset_path).expanduser().resolve()
        if not resolved.exists():
            raise FileNotFoundError(f"Explicit dataset_path does not exist: {resolved}")
        return resolved

    root = Path(project_root or Path.cwd()).expanduser().resolve()
    package = Path(package_dir).expanduser().resolve()
    dataset_info = dict(manifest.get("dataset", {}))
    finir_rel = dataset_info.get("finportfolio_ir_relative_path")
    copy_name = dataset_info.get("copy_name", "rl_panel_codex_rule_text_features.csv")
    local_source = dataset_info.get("local_source_path")

    candidates: list[Path] = []
    env_value = os.environ.get("PPO_TEXT_PANEL_PATH")
    if env_value:
        candidates.append(Path(env_value))
    if local_source:
        candidates.append(Path(local_source))
    if finir_rel:
        for ancestor in _candidate_ancestors(root):
            candidates.extend(
                [
                    ancestor / "FinPortfolio_IR" / str(finir_rel),
                    ancestor / str(finir_rel),
                ]
            )
    candidates.extend(
        [
            package / str(copy_name),
            package.parent.parent / str(copy_name),
            root / str(copy_name),
        ]
    )
    found = _first_existing(candidates)
    if found is None:
        raise FileNotFoundError(
            "Could not locate the merge-ready PPO panel. Set PPO_TEXT_PANEL_PATH "
            "or copy rl_panel_codex_rule_text_features.csv into the screening package."
        )
    return found


def _install_custom_feature_registry_patch(manifest: Mapping[str, Any]) -> None:
    import dow30_horizon_a as horizon
    import dow30_notebook_research_runner as notebook_runner_module
    import dow30_project_research as project_research
    import dow30_research_support as research_support

    if not hasattr(horizon, "_fingpt_screening_original_registry_builder"):
        setattr(
            horizon,
            "_fingpt_screening_original_registry_builder",
            horizon.build_controlled_feature_registry,
        )
    if not hasattr(horizon, "_fingpt_screening_original_infer_feature_metadata"):
        setattr(
            horizon,
            "_fingpt_screening_original_infer_feature_metadata",
            horizon.infer_feature_metadata,
        )

    original_builder = getattr(horizon, "_fingpt_screening_original_registry_builder")
    original_infer = getattr(horizon, "_fingpt_screening_original_infer_feature_metadata")

    custom_specs: dict[str, dict[str, Any]] = {}
    for experiment in manifest.get("experiments", []):
        name = str(experiment.get("name"))
        if name not in CUSTOM_TEXT_FEATURE_SETS:
            continue
        custom = dict(CUSTOM_TEXT_FEATURE_SETS[name])
        custom["text_feature_columns"] = tuple(experiment.get("text_feature_columns", []))
        custom_specs[name] = custom

    def patched_build_controlled_feature_registry(
        feature_groups: Mapping[str, Sequence[str]],
        *,
        include_event_calendar: bool = True,
        candidate_feature_families: Sequence[str] | None = None,
        include_feature_sets: Sequence[str] | None = None,
    ):
        registry = original_builder(
            feature_groups,
            include_event_calendar=include_event_calendar,
            candidate_feature_families=candidate_feature_families,
            include_feature_sets=None,
        )
        groups = {
            group_name: _dedupe(columns)
            for group_name, columns in dict(feature_groups).items()
        }
        base = groups.get("base", ())
        macro = groups.get("macro", ())
        for feature_set_name, custom in custom_specs.items():
            group_name = str(custom["group_name"])
            text_columns = groups.get(group_name, ())
            if not text_columns:
                text_columns = _dedupe(custom.get("text_feature_columns", ()))
            if not text_columns:
                continue
            registry[feature_set_name] = horizon.FeatureSetSpec(
                name=feature_set_name,
                columns=_dedupe(base + macro + text_columns),
                feature_family=str(custom["feature_family"]),
                is_negative_control=False,
                feature_set_description=str(custom["description"]),
                source_groups=("base", "macro", group_name),
            )
        if include_feature_sets is not None:
            requested = tuple(str(name) for name in include_feature_sets)
            registry = OrderedDict((name, spec) for name, spec in registry.items() if name in requested)
        return registry

    def patched_infer_feature_metadata(feature_set_name: Any) -> dict[str, Any]:
        name = str(feature_set_name)
        if name in custom_specs:
            custom = custom_specs[name]
            return {
                "feature_set": name,
                "feature_family": str(custom["feature_family"]),
                "is_negative_control": False,
                "feature_set_description": str(custom["description"]),
            }
        return original_infer(feature_set_name)

    horizon.build_controlled_feature_registry = patched_build_controlled_feature_registry
    project_research.build_controlled_feature_registry = patched_build_controlled_feature_registry
    research_support.build_controlled_feature_registry = patched_build_controlled_feature_registry
    horizon.infer_feature_metadata = patched_infer_feature_metadata
    notebook_runner_module.infer_feature_metadata = patched_infer_feature_metadata


def _build_feature_groups(default_feature_groups: Mapping[str, Sequence[str]], manifest: Mapping[str, Any]):
    groups = OrderedDict(
        (str(name), tuple(str(column) for column in columns))
        for name, columns in default_feature_groups.items()
    )
    for experiment in manifest.get("experiments", []):
        name = str(experiment.get("name"))
        custom = CUSTOM_TEXT_FEATURE_SETS.get(name)
        if custom is None:
            continue
        text_columns = tuple(str(column) for column in experiment.get("text_feature_columns", []))
        groups[str(custom["group_name"])] = text_columns
    return groups


def _validate_feature_columns(df_columns: Sequence[str], experiment: Mapping[str, Any]) -> list[str]:
    available = {str(column) for column in df_columns}
    return [str(column) for column in experiment.get("feature_columns", []) if str(column) not in available]


def run_screening_experiment(
    variant_name: str,
    *,
    project_root: str | Path | None = None,
    package_dir: str | Path | None = None,
    ablation_root: str | Path | None = None,
    dataset_path: str | Path | None = None,
    output_root: str | Path | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Run one Huawei PPO screening variant through the existing PPO runner."""

    project = Path(project_root or Path.cwd()).expanduser().resolve()
    package = resolve_package_dir(project, package_dir)
    manifest = load_manifest(package)
    experiment = get_experiment(manifest, variant_name)
    runner_kwargs = dict(manifest.get("ppo_runner", {}).get("runner_kwargs", {}))
    dataset = resolve_dataset_path(manifest, package, project, dataset_path)
    ablation = resolve_ablation_root(project, ablation_root)

    output_base = Path(output_root).expanduser().resolve() if output_root else package
    output_dir = output_base / str(experiment.get("output_dir"))
    output_dir.mkdir(parents=True, exist_ok=True)

    resolution = {
        "variant_name": str(variant_name),
        "project_root": str(project),
        "package_dir": str(package),
        "dataset_path": str(dataset),
        "ablation_root": str(ablation),
        "output_dir": str(output_dir),
        "dry_run": bool(dry_run),
    }
    (output_dir / "runtime_resolution.json").write_text(
        json.dumps(resolution, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    if dry_run:
        return resolution

    if str(ablation) not in sys.path:
        sys.path.insert(0, str(ablation))

    import pandas as pd
    from dow30_notebook_research_runner import build_notebook_research_runner
    from dow30_reference_notebook_runtime import load_reference_notebook_runtime
    from dow30_research_support import DEFAULT_FEATURE_GROUPS

    _install_custom_feature_registry_patch(manifest)
    feature_groups = _build_feature_groups(DEFAULT_FEATURE_GROUPS, manifest)

    df = pd.read_csv(dataset)
    missing_features = _validate_feature_columns(df.columns, experiment)
    if missing_features:
        raise ValueError(f"{variant_name} missing dataset feature columns: {missing_features}")

    notebook_ns = load_reference_notebook_runtime()
    research_runner = build_notebook_research_runner(notebook_ns)
    seed = int(experiment.get("seed", (runner_kwargs.get("seeds") or [42])[0]))

    launch_kwargs = {
        "base_config_name": runner_kwargs.get("base_config_name", "custom_custom"),
        "output_dir": output_dir,
        "feature_groups": feature_groups,
        "candidate_feature_families": tuple(runner_kwargs.get("candidate_feature_families", [])),
        "feature_set_filter": (variant_name,),
        "seeds": (seed,),
        "total_timesteps": int(runner_kwargs.get("total_timesteps", 200_000)),
        "max_folds": runner_kwargs.get("max_folds"),
        "es_mode": runner_kwargs.get("es_mode", "relaxed"),
        "dropout_p": float(runner_kwargs.get("dropout_p", 0.1)),
        "eval_freq": int(runner_kwargs.get("eval_freq", 8192)),
        "checkpoint_freq": int(runner_kwargs.get("checkpoint_freq", 4096)),
        "checkpoint_selection_rule": runner_kwargs.get(
            "checkpoint_selection_rule",
            "checkpoint_robust_score",
        ),
        "domain_reward_scaling": dict(runner_kwargs.get("domain_reward_scaling", {})),
        "action_regularization": dict(runner_kwargs.get("action_regularization", {})),
        "verbose": int(runner_kwargs.get("verbose", 0)),
    }

    result = research_runner(df=df, **launch_kwargs)
    expected_artifacts = {
        "walk_forward_results": output_dir / "walk_forward_results.csv",
        "unique_run_level_results": output_dir / "unique_run_level_results.csv",
        "walk_forward_daily_test_returns": output_dir / "walk_forward_daily_test_returns.csv",
        "walk_forward_test_actions": output_dir / "walk_forward_test_actions.csv",
        "walk_forward_test_observations": output_dir / "walk_forward_test_observations.csv",
        "benchmark_suite_daily": output_dir / "benchmark_suite_daily.csv",
        "artifact_index": output_dir / "artifact_index.json",
    }
    run_manifest = {
        **resolution,
        "completed_at_utc": datetime.now(timezone.utc).isoformat(),
        "runner_kwargs": {
            key: (str(value) if isinstance(value, Path) else value)
            for key, value in launch_kwargs.items()
            if key not in {"feature_groups"}
        },
        "feature_count": int(len(experiment.get("feature_columns", []))),
        "text_feature_count": int(len(experiment.get("text_feature_columns", []))),
        "result_keys": list(result.keys()) if isinstance(result, Mapping) else [],
        "artifacts": {
            name: {
                "path": str(path),
                "exists": path.exists(),
                "size_bytes": path.stat().st_size if path.exists() else 0,
            }
            for name, path in expected_artifacts.items()
        },
    }
    (output_dir / "run_manifest.json").write_text(
        json.dumps(run_manifest, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    return run_manifest

